export enum ContractStatus {
  BORRADOR = 'BORRADOR',
  PENDIENTE = 'PENDIENTE',
  FIRMADO = 'FIRMADO',
  ACTIVO = 'ACTIVO',
  POR_VENCER = 'POR_VENCER',
  VENCIDO = 'VENCIDO',
  RENOVADO = 'RENOVADO',
  FINALIZADO = 'FINALIZADO',
  CANCELADO = 'CANCELADO',
  SUSPENDIDO = 'SUSPENDIDO',
}
